# This is a basic workflow to help you get started with Actions

name: SA_ALD_Windows_Edge

on:
  #schedule:
  #  - cron:  '10 3,15 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 1
      - name: 🔨 Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64
          
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - name: Install dependencies
        run: choco install git 7zip -y
      - name: Install Tesseract OCR
        run: |
          $tesseract_url = "https://github.com/UB-Mannheim/tesseract/wiki"
          $tesseract_installer = "tesseract-ocr-setup-v4.00.00dev.exe"
          Invoke-WebRequest -Uri $tesseract_url -OutFile $tesseract_installer
          Start-Process -Wait -FilePath $tesseract_installer -ArgumentList '/SILENT' # Silent install

          
      - name: DO RUN
        run: java -jar BIN/SeleniumAction.jar ALD_WIN_EDGE
      - name: 🚀 Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🚀 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}.git
