# This is a basic workflow to help you get started with Actions

name: SA_ALD_Ubuntu_Chrome

on:
  schedule:
    - cron:  '10 3,6,15,18 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 1
          
      - name: 🔨 Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64
          
      - name: install chrome
        run: |
          set -ex
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          rm ./google-chrome-stable_current_amd64.deb
          
      - name: Install Tesseract OCR (v5 default)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Create Tesseract 4.00 tessdata directory
        run: sudo mkdir -p /usr/share/tesseract-ocr/4.00/tessdata

      - name: Download Tesseract 4.00 eng.traineddata
        run: |
          sudo curl -L -o /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata \
            https://github.com/tesseract-ocr/tessdata/raw/4.00/eng.traineddata
          sudo chmod 644 /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata

      - name: Check version and tessdata path
        run: |
          tesseract --version
          find /usr/share -type d -name tessdata
          
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Check where tessdata is
        run: |
          find /usr/share -type d -name tessdata
          
      - name: List installed Tesseract data files
        run: |
          ls -al /usr/share/tesseract-ocr/4.00/tessdata || ls -al /usr/share/tesseract-ocr/tessdata

      - name: DO RUN
        run: java -jar BIN/SeleniumAction.jar ALD_UBU_CHROME
        
      - name: 🚀 Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🚀 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}.git
