name: SA_FAB_SALE

on:
  schedule:
    - cron:  '45 6 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 1
          
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-chromedriver: true
          
      - name: Install dependencies
        run: |
          cd BIN/FAB_PY
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Python script
        run: |
          cd BIN/FAB_PY/src
          python drissionpage_parser2.py
