# This is a basic workflow to help you get started with Actions

name: SA_TC_Ubuntu_Chrome

on:
  schedule:
    - cron:  '0 7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 1
      - name: 🔨 Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64
      - name: install chrome
        run: |
          set -ex
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          rm ./google-chrome-stable_current_amd64.deb
      - name: DO RUN 1
        run: java -jar BIN/TC/SA_TC_Ubuntu_Chrome.jar 1
      - name: DO RUN 2
        run: java -jar BIN/TC/SA_TC_Ubuntu_Chrome.jar 2
      - name: DO RUN 3
        run: java -jar BIN/TC/SA_TC_Ubuntu_Chrome.jar 3
      - name: 🚀 Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🚀 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}.git
