# This is a basic workflow to help you get started with Actions

name: SA_TC_Windows_Edge

on:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 1
      - name: 🔨 Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          architecture: x64
      - name: DO RUN 1
        run: java -jar BIN/SeleniumAction.jar TC_WIN_EDGE 1
      - name: DO RUN 2
        run: java -jar BIN/SeleniumAction.jar TC_WIN_EDGE 2
      - name: DO RUN 3
        run: java -jar BIN/SeleniumAction.jar TC_WIN_EDGE 3
      - name: DO RUN 4
        run: java -jar BIN/SeleniumAction.jar TC_WIN_EDGE 4
      - name: DO RUN 5
        run: java -jar BIN/SeleniumAction.jar TC_WIN_EDGE 5
      - name: 🚀 Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🚀 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.REPO_TOKEN }}@github.com/${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}.git
